services:
  - type: web
    name: vesta-yangin-takip
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && PLAYWRIGHT_BROWSERS_PATH=0 python -m playwright install chromium
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: vestaadmin
      - key: ADMIN_PASSWORD
        value: degistir-beni-2026
      - key: DATABASE_URL
        fromDatabase:
          name: vesta-yangin-db
          property: connectionString
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "0"

databases:
  - name: vesta-yangin-db
    plan: free
